<?php
/**
 * Guidance Core Module
 *
 * @author    Guidance Magento Team <magento@guidance.com>
 * @category  Guidance
 * @package   Guidance_Core
 * @copyright Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */

/**
 * @var $this Guidance_Core_Block_Adminhtml_Audit_Modules
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Module Summary') ?></h4></div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="products_grid">
                <thead>
                    <tr class="headings">
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Code Pool') ?></span></th>
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Module Count') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getModuleCodepools() as $_title => $_modules): ?>
                    <tr>
                        <td><?php echo $this->__('%s modules', ucwords($_title)); ?></td>
                        <td class="a-right"><?php echo count($_modules) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Rewrite Summary') ?></h4></div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="products_grid">
                <thead>
                    <tr class="headings">
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Rewrite Type') ?></span></th>
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Count') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getSystemRewrites() as $_title => $_modules): ?>
                    <tr>
                        <td><?php echo $this->__(ucwords($_title)); ?></td>
                        <td class="a-right"><?php echo count($_modules) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>