<?php
/**
 * Guidance Core Module
 *
 * @author    Guidance Magento Team <magento@guidance.com>
 * @category  Guidance
 * @package   Guidance_Core
 * @copyright Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */

/**
 * @var $this Guidance_Core_Block_Adminhtml_Audit_Modules
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Module Summary') ?></h4></div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="products_grid">
                <thead>
                    <tr class="headings">
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Code Pool') ?></span></th>
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Count') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getModuleCodepools() as $_title => $_modules): ?>
                    <tr>
                        <td><?php echo $this->__('%s modules', ucwords($_title)); ?></td>
                        <td class="a-right"><?php echo count($_modules) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>
<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Rewrite Summary') ?></h4></div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="products_grid">
                <thead>
                    <tr class="headings">
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Rewrite Type') ?></span></th>
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Count') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getSystemRewrites() as $_title => $_modules): ?>
                    <tr>
                        <td><?php echo $this->__(ucwords($_title)); ?></td>
                        <td class="a-right"><?php echo count($_modules) ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>
<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td><h3 class="head-dashboard"><?php echo $this->__('Module Detail') ?></h3></td>
            </tr>
        </tbody>
    </table>
</div>

<?php foreach ($this->getModuleCodepools() as $codePoolType => $modules): ?>
    <?php 
        if ($codePoolType == 'core') {
            continue;
        }
    ?>
    <h3><?php echo $this->__('%s code pool', ucwords($codePoolType)); ?></h3>
    <?php if (count($modules)): ?>
        <?php foreach ($modules as $moduleName): ?>
        <div class="module">
            <h4><?php echo $moduleName; ?></h4>
            <?php foreach ($this->getModuleRewrites() as $rewriteType => $rewrites): ?>
                <?php if (isset($rewrites[$moduleName]) && count($rewrites[$moduleName])): ?>
                    <p class="rewrite"><?php echo $this->__('Rewritten %s:', ucwords($rewriteType)); ?></p>
                    <ul>
                    <?php foreach ($rewrites[$moduleName] as $rewrite): ?>
                        <li>
                            <?php echo $rewrite['alias']; ?> =&gt; <?php echo $rewrite['class']; ?>
                            <?php $methods = $this->getOverridenMethods($rewrite['class']); ?>
                            <?php if (count($methods)): ?>
                            <ul>
                                <?php foreach ($methods as $method): ?>
                                <li><?php echo $method; ?></li>
                                <?php endforeach; ?>
                            </ul>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p>No modules found</p>
    <?php endif; ?>
<?php endforeach; ?>