<?php
/**
 * Guidance Core Module
 *
 * @author    Guidance Magento Team <magento@guidance.com>
 * @category  Guidance
 * @package   Guidance_Core
 * @copyright Copyright (c) 2014 Guidance Solutions (http://www.guidance.com)
 */

/**
 * @var $this Guidance_Core_Block_Adminhtml_Audit_Stats
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td><h3 class="head-dashboard"><?php echo $this->__('Magento Audit') ?></h3></td>
            </tr>
        </tbody>
    </table>
</div>

<div class="entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Statistics') ?></h4></div>
    <fieldset class="np">
        <div class="grid np">
            <table cellspacing="0" style="border:0;" id="statistics_grid">
                <thead>
                    <tr class="headings">
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Collection') ?></span></th>
                        <th class="no-link"><span class="nobr"><?php echo $this->__('Count') ?></span></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCounts() as $_title => $_size): ?>
                    <tr>
                        <td><?php echo $_title; ?></td>
                        <td class="a-right"><?php echo $_size ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>